## Importa Biblioteca
Esta célula importa a biblioteca **Pandas** e lê o arquivo `hotel_bookings.csv`, criando o DataFrame `df` com todos os dados da planilha.

In [ ]:
import pandas as pd

df = pd.read_csv("hotel_bookings.csv")

## Dados dos por pais
Esta célula agrupa os dados por país e calcula a média das colunas numéricas para cada país.

In [12]:
df.groupby("country").mean(numeric_only=True).round(2)

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
country,,,,,,,,,,,,,,,,,,,,
ABW,0.00,126.00,2016.50,22.50,16.00,1.00,2.50,2.50,0.00,0.00,0.00,0.00,0.00,0.00,12.00,NaN,0.0,128.34,0.00,1.50
AGO,0.57,23.10,2016.21,22.05,15.20,2.28,5.83,1.57,0.21,0.01,0.05,0.04,0.09,0.38,26.68,215.9,0.0,117.12,0.03,0.51
AIA,0.00,0.00,2016.00,28.00,8.00,2.00,2.00,2.00,2.00,0.00,0.00,0.00,0.00,0.00,8.00,NaN,0.0,265.00,0.00,0.00
ALB,0.17,103.42,2016.17,24.42,16.75,1.00,2.33,1.75,0.00,0.08,0.00,0.00,0.00,0.25,80.80,233.0,0.0,84.35,0.00,0.67
AND,0.71,47.00,2016.57,24.43,14.71,1.29,3.14,2.14,0.57,0.00,0.00,0.00,0.00,0.14,175.43,NaN,0.0,202.65,0.29,0.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VGB,1.00,109.00,2016.00,32.00,5.00,1.00,2.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,9.00,NaN,0.0,100.50,0.00,0.00
VNM,0.25,84.12,2016.38,35.00,19.00,0.62,2.00,2.12,0.00,0.00,0.00,0.00,0.00,0.12,104.62,NaN,0.0,123.27,0.00,0.62
ZAF,0.39,70.15,2016.45,24.55,16.11,0.90,2.04,1.79,0.21,0.00,0.01,0.00,0.01,0.28,78.11,218.0,0.0,111.15,0.05,0.78
ZMB,0.50,68.50,2015.50,29.00,14.00,1.50,2.50,2.00,1.00,0.00,0.00,0.00,0.00,0.00,124.50,NaN,0.0,101.88,0.00,2.00
ZWE,0.50,83.00,2016.50,30.00,17.00,0.25,2.25,2.00,0.00,0.00,0.00,0.00,0.00,1.00,96.00,NaN,0.0,85.31,0.00,0.25

## Conta a Frequencia
Esta célula conta a frequência de cada valor da coluna analisada (como país, agente ou empresa).

In [13]:
df["country"].value_counts(dropna=False)

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
NCL        1
KIR        1
SDN        1
ATF        1
SLE        1
Name: count, Length: 178, dtype: int64

## Calculo das Reservas
Esta célula calcula a porcentagem de reservas por país (`country`).

In [11]:
df["country"].value_counts(normalize=True, dropna=False).mul(100).round(2)

country
PRT    40.70
GBR    10.16
FRA     8.72
ESP     7.18
DEU     6.10
       ...
NCL     0.00
KIR     0.00
SDN     0.00
ATF     0.00
SLE     0.00
Name: proportion, Length: 178, dtype: float64

## Ordena os valores da coluna menor para o maior
Esta célula ordena do `menor para o maior` os valores da coluna `adr` (preço médio da diária) para encontrar as maiores ou menores diárias.

In [10]:
df["adr"].sort_values().head(10)

14969    -6.38
0         0.00
2534      0.00
2536      0.00
33283     0.00
101624    0.00
2595      0.00
33205     0.00
2691      0.00
33107     0.00
Name: adr, dtype: float64

## Ordena os valores da coluna maior para o menor
Esta célula ordena do `maior para o menor` os valores da coluna `adr` (preço médio da diária) para encontrar as maiores ou menores diárias.

In [9]:
df["adr"].sort_values(ascending=False).head(10)

48515     5400.00
111403     510.00
15083      508.00
103912     451.50
13142      450.00
13391      437.00
39155      426.25
39568      402.00
39118      397.38
13323      392.00
Name: adr, dtype: float64

## Ordena a coluna adults
Esta célula ordena a coluna `adults` para encontrar reservas com mais adultos.

In [8]:
df["adults"].sort_values(ascending=False).head(10)

2173    55
1643    50
1539    40
1917    27
1962    27
2003    26
1752    26
2164    26
1587    26
1884    26
Name: adults, dtype: int64

## Procura registros com valor
Esta célula identifica qual reserva possui uma diária negativa (para investigar um possível erro nos dados) `adr`, identificando possíveis inconsistências nos dados.

In [7]:
df[df["adr"] < 0][["hotel", "is_canceled", "adr"]]

              hotel  is_canceled   adr
14969  Resort Hotel            0 -6.38

## Comentário da célula
Esta célula verifica quantas reservas apresentam o problema que a celula de cima achou.

In [6]:
(df["adr"] < 0).sum()

np.int64(1)

## Exibe todos os dados de uma linha
Esta célula exibe todos os dados de uma linha específica do DataFrame para analisar um caso em detalhe.

In [5]:
df.loc[14969]

hotel                                Resort Hotel
is_canceled                                     0
lead_time                                     195
arrival_date_year                            2017
arrival_date_month                          March
arrival_date_week_number                       10
arrival_date_day_of_month                       5
stays_in_weekend_nights                         4
stays_in_week_nights                            6
adults                                          2
children                                      0.0
babies                                          0
meal                                           BB
country                                       GBR
market_segment                             Groups
distribution_channel                       Direct
is_repeated_guest                               1
previous_cancellations                          0
previous_bookings_not_canceled                  2
reserved_room_type                              A
assigned_room_type                              H
booking_changes                                 2
deposit_type                           No Deposit
agent                                       273.0
company                                       NaN
days_in_waiting_list                            0
customer_type                     Transient-Party
adr                                         -6.38
required_car_parking_spaces                     0
total_of_special_requests                       0
reservation_status                      Check-Out
reservation_status_date                2017-03-15
Name: 14969, dtype: object

## Quantidade total
Esta célula exibe a quantidade de **linhas e colunas** do DataFrame (`df`).

In [ ]:
df.shape

(119390, 32)

## Ordena a coluna lead_time
Esta célula ordena a coluna `lead_time` para encontrar reservas feitas com maior antecedência.

In [ ]:
df["lead_time"].sort_values(ascending=False).head(10)

1        737
4182     709
65240    629
65249    629
65245    629
65254    629
65253    629
65252    629
65241    629
65250    629
Name: lead_time, dtype: int64

## Conta quantas colunas existem
Esta célula conta quantas colunas existem de cada tipo de dado (`object`, `int64`, `float64`, etc.).

In [ ]:
df.dtypes.value_counts()

int64      16
str        12
float64     4
Name: count, dtype: int64

## Mostra o tipo de dado
Esta célula mostra o tipo de dado de cada coluna.

In [ ]:
df.select_dtypes(include="number").columns

Index(['is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='str')

## Estatísticas descritivas das colunas numéricas
Esta célula gera estatísticas descritivas das colunas numéricas (média, mínimo, máximo, quartis, desvio padrão, etc.).

In [ ]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

## Quais agências ou agentes realizaram mais reservas
Esta célula analisar quais agências ou agentes realizaram mais reservas e quantas reservas não possuem agente cadastrado.

In [ ]:
df["agent"].value_counts(dropna=False).head(10)

agent
9.0      31961
NaN      16340
240.0    13922
1.0       7191
14.0      3640
7.0       3539
6.0       3290
250.0     2870
241.0     1721
28.0      1666
Name: count, dtype: int64

## Descobrir quais países são a maioria dos hóspedes
Esta célula procura descobrir quais países são a maioria dos hóspedes , identificando os 10 países com maior número de reservas.

In [ ]:
df["country"].value_counts(dropna=False).head(10)

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
ITA     3766
IRL     3375
BEL     2342
BRA     2224
NLD     2104
Name: count, dtype: int64

## conta quantas reservas foram feitas por cada empresa
Esta célula conta quantas reservas foram feitas por cada empresa (company) e mostra as 10 empresas que mais aparecem , incluindo os valores vazios (NaN).

In [ ]:
df["company"].value_counts(dropna=False).head(10)

company
NaN      112593
40.0        927
223.0       784
67.0        267
45.0        250
153.0       215
174.0       149
219.0       141
281.0       138
154.0       133
Name: count, dtype: int64

## Valores nulos
Esta célula calcula a porcentagem de valores nulos e ordena da maior para a menor.

In [ ]:
(df.isna().mean() * 100).sort_values(ascending=False)

company                           94.306893
agent                             13.686238
country                            0.408744
children                           0.003350
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
hotel                              0.000000
previous_cancellations             0.000000
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
previous_bookings_not_canceled     0.000000
is_repeated_guest                  0.000000
is_canceled                        0.000000
distribution_channel               0.000000
market_segment                     0.000000
meal                               0.000000
babies                             0.000000
adults                             0.000000
stays_in_week_nights               0.000000
stays_in_weekend_nights            0.000000
arrival_date_day_of_month          0.000000
arrival_date_week_number           0.000000
arrival_date_month                 0.000000
arrival_date_year                  0.000000
lead_time                          0.000000
reservation_status_date            0.000000
dtype: float64

## Quantidade de Nulos 
Esta célula mostra a quantidade de valores nulos que a celula de cima pegou.

In [ ]:
df.isna().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
hotel                                  0
previous_cancellations                 0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
previous_bookings_not_canceled         0
is_repeated_guest                      0
is_canceled                            0
distribution_channel                   0
market_segment                         0
meal                                   0
babies                                 0
adults                                 0
stays_in_week_nights                   0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
arrival_date_week_number               0
arrival_date_month                     0
arrival_date_year                      0
lead_time                              0
reservation_status_date                0
dtype: int64

## Tipo de dado de cada coluna.
Esta célula mostra o tipo de dado de cada coluna.

In [ ]:
df.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

## Porcentagem de valores nulos por coluna.
Esta célula calcula a porcentagem de valores nulos em cada coluna.

In [ ]:
df.isna().mean() * 100

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.003350
babies                             0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

## Calcula quantos valores
Esta célula conta quantos valores vazios (NaN) existem em cada coluna.

In [ ]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

## Conta quantos valores diferentes
Esta célula conta quantos valores diferentes existem em cada coluna.

In [ ]:
df.nunique()

hotel                                2
is_canceled                          2
lead_time                          479
arrival_date_year                    3
arrival_date_month                  12
arrival_date_week_number            53
arrival_date_day_of_month           31
stays_in_weekend_nights             17
stays_in_week_nights                35
adults                              14
children                             5
babies                               5
meal                                 5
country                            177
market_segment                       8
distribution_channel                 5
is_repeated_guest                    2
previous_cancellations              15
previous_bookings_not_canceled      73
reserved_room_type                  10
assigned_room_type                  12
booking_changes                     21
deposit_type                         3
agent                              333
company                            352
days_in_waiting_list               128
customer_type                        4
adr                               8879
required_car_parking_spaces          5
total_of_special_requests            6
reservation_status                   3
reservation_status_date            926
dtype: int64

## Informações gerais dos nao nulos 
Esta célula mostra informações gerais do DataFrame: quantidade de valores não nulos, tipos de dados e uso de memória.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

## Lista o nome
Esta célula lista o nome de todas as colunas existentes na planilha.

In [ ]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='str')

## Mostra as 5 primeiras linhas
Esta célula mostra as **5 primeiras linhas** da tabela para verificar se o arquivo foi carregado corretamente e conhecer a estrutura dos dados.

In [ ]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03